version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4003:3000"
    environment:
      - NODE_ENV=production
      # - API_BASE_URL=http://5.75.128.196:8000 # Eğer IP ile girecekseniz bunu frontend .env dosyasından da ayarlayabilirsiniz.
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8080" # serversideup image varsayılan olarak 8080 portunu kullanır. Dışarıya 8000 olarak açıyoruz.
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      # Veritabanı ve APP_KEY gibi hassas ayarları Coolify'da "Environment Variables" sekmesinden girmelisiniz.
    restart: unless-stopped
    volumes:
      # SQLite kullanıyorsanız veritabanının kaybolmaması için volume tanımlayabilirsiniz.
      # MySQL vb. kullanacaksanız buraya gerek yok.
      - ./backend/database:/var/www/html/database
